import java.util.Scanner;

public class AppFolhaPagamento {
    public static void main(String[] args) throws Exception {
        Scanner in = new Scanner(System.in);
        System.out.println("Digite seu nome: ");
        System.out.println("Digite seu CPF: ");
        System.out.println("Digite seu salário bruto: ");
        System.out.println("Digite 1 para CLT, 2 para Estagiário e 3 para Prestador de Serviço (PJ): ");
        
        //exibirResumo()
    }
}
